import { test, expect } from "@playwright/test";
import { todo } from "node:test";

test.describe("Testing Jam-Board", () => {
  test.beforeEach(async ({ page }) => {
    await page.goto("https://jam.up.railway.app/login");
    const title = page.getByText("Login to Your Account");
    await expect(title).toBeVisible();
    const userInput = page.locator("#username");
    await expect(userInput).toBeVisible();
    await userInput.fill("jleee5");
    const passwordInput = page.locator("#password");
    await expect(passwordInput).toBeVisible();
    await passwordInput.fill("password123");
    const loginButton = page.getByRole("button", { name: "Login" });
    await expect(loginButton).toBeVisible();
    await loginButton.click();
  });
  test("Adding a work item", async ({ page }) => {
    const boardButton = page.getByRole("button", { name: "Create Board" });
    await expect(boardButton).toBeVisible();
    await boardButton.click();
    const createBoard = page.locator("h2", { hasText: "Create a New Board" });
    await expect(createBoard).toBeVisible();
    const boardNameInput = page.locator("#boardName");
    await expect(boardNameInput).toBeVisible();
    await boardNameInput.fill("testing");
    await expect(boardButton).toBeVisible();
    const createBoard2 = page.getByRole("button", { name: "Create Board" });
    await expect(createBoard2).toBeVisible();
    await createBoard2.click();
    const myBoard = page.locator("h3", { hasText: "testing" });
    await expect(myBoard).toBeVisible();
    await myBoard.click();
    const toDo = page.locator("h2", { hasText: "To Do" });
    await expect(toDo).toBeVisible();
    const listOfItems = await page.getByText("Add Work Item").all();
    expect(listOfItems.length > 0).toBeTruthy();
    console.log(listOfItems);
    await listOfItems[0].click();
    const item = page.getByLabel("title");
    await expect(item).toBeVisible();
    const itemInput = page.getByLabel("title");
    await itemInput.fill("Fixing");
    const createButton = page.getByRole("button", { name: "Create" });
    await expect(createButton).toBeVisible();
    await createButton.click();
    const myBoardsButton = page.getByText("My Boards");
    await expect(myBoardsButton).toBeVisible();
    await myBoardsButton.click();
  });
});
